services:
  ventas-service:
    build: ./ventas_service
    ports:
      - "8001:8000"
    depends_on:
      - consul

  inventario-service:
    build: ./inventario_service
    ports:
      - "8002:8000"
    depends_on:
      - consul

  clientes-service:
    build: ./clientes_service
    ports:
      - "8003:8000"
    depends_on:
      - consul

  consul:
    image: consul:1.15.0
    ports:
      - "8500:8500"
    volumes:
      - ./consul/config:/consul/config

  nginx:
    image: nginx:1.25.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ventas-service
      - inventario-service
      - clientes-service